---
# tasks file for ajsalminen.nginx

- name: Install nginx.
  apt:
    pkg: nginx
    state: "{{ nginx_install_state }}"
    update_cache: yes
    cache_valid_time: "{{ APT_CACHE_VALID_TIME }}"

- name: Install nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0664
  notify: restart nginx


- name: Disable default nginx site
  file: state=absent path=/etc/nginx/sites-enabled/default
  when: nginx_disable_default == True
  notify: restart nginx
